const fs = require('fs');
const path = require('path');

const rootDir = 'c:/Users/Lenovo/Downloads/playsphere-main-main/playsphere-main-main/PlaySphere-Documentation';

const docs = {
  // 13-Performance
  '13-Performance/Performance Optimization.md': `# Performance Optimization\n\nPlaySphere is optimized for high-speed delivery and sub-second interactions.\n\n## Core Optimizations\n1. **Server-Side Rendering (SSR):** Next.js App Router renders pages dynamically on Vercel's Edge, eliminating client-side data fetching waterfalls for public pages (e.g., the Homepage).\n2. **React Server Components (RSC):** Heavy libraries are kept on the server, significantly reducing the JavaScript payload sent to the client browser.\n3. **Optimistic Updates:** UI state is mutated locally before server confirmation (e.g., during booking slot selection) to ensure the interface feels immediate.`,

  '13-Performance/Image Optimization.md': `# Image Optimization\n\nPlaySphere strictly utilizes the Next.js \`<Image />\` component for all graphical assets.\n\n## Implementation Details\n- **WebP/AVIF Conversion:** Images uploaded to Firebase Storage or served locally are automatically converted to modern, highly compressed formats by the Next.js image optimization API.\n- **Lazy Loading:** Images below the fold are natively lazy-loaded by default.\n- **Responsive Sizing:** \`sizes\` props are utilized to ensure the browser only downloads the resolution necessary for the current viewport (e.g., downloading a 300px image for mobile instead of the 1200px original).`,

  '13-Performance/Lazy Loading.md': `# Lazy Loading\n\n## Component Level\nPlaySphere utilizes Next.js dynamic imports (\`next/dynamic\`) for heavy, non-critical components to defer their loading until they are required by the user.\n\n\`\`\`javascript\nimport dynamic from 'next/dynamic';\n\n// The Payment Modal is only loaded when the user clicks 'Book Now'\nconst PaymentModal = dynamic(() => import('@/components/booking/PaymentModal'), {\n  ssr: false,\n});\n\`\`\`\n\n## Route Level\nRoute-based code splitting is handled automatically by the Next.js App Router, ensuring users only download the JavaScript strictly necessary for the page they are visiting.`,

  '13-Performance/Code Splitting.md': `# Code Splitting\n\nCode splitting is achieved natively via Webpack/Turbopack under the Next.js build step.\n\n## Third-Party Libraries\nHeavy third-party libraries (e.g., \`xlsx\`, \`framer-motion\`) are isolated. If they are only used on specific routes (like the Admin Dashboard for exporting Excel files), they are NOT included in the global \`_app\` or \`layout\` bundles, ensuring the public-facing booking flow remains lightweight.`,

  '13-Performance/Firestore Optimization.md': `# Firestore Optimization\n\nFirestore charges per document read, making query optimization a financial and performance necessity.\n\n## Strategies Implemented\n1. **Denormalization:** Frequently accessed relational data (like \`turfName\` in a Booking document) is duplicated to avoid secondary lookup queries.\n2. **Shallow Fetching:** The UI limits queries using \`limit(50)\` and implements pagination via \`startAfter\` cursors to prevent massive data dumps on the client.\n3. **Composite Indexes:** Complex queries (like sorting an owner's bookings by date) utilize pre-built composite indexes to ensure query execution time is proportional to the result set size, not the total collection size.`,

  '13-Performance/SEO.md': `# SEO (Search Engine Optimization)\n\n## Next.js Metadata API\nPlaySphere dynamically generates HTML \`<head>\` metadata via the Next.js \`generateMetadata\` API.\n\n## Key Implementations\n- **Dynamic Titles/Descriptions:** Turf detail pages dynamically inject the turf's name, location, and description into the title tags.\n- **Open Graph (OG) Tags:** Facebook and Twitter card metadata is populated for rich link previews when users share a turf URL.\n- **Semantic HTML:** Strict adherence to hierarchical heading structures (\`<h1>\`, \`<h2>\`) and accessible ARIA labels to boost crawler indexing.`,

  // 14-Backup-Recovery
  '14-Backup-Recovery/Backup Strategy.md': `# Backup Strategy\n\n> **Note:** Documenting standard Google Cloud Backup procedures for Firestore.\n\n## Automated Backups\nFirestore data is highly durable. For disaster recovery, Google Cloud Platform (GCP) Point-in-Time Recovery (PITR) should be enabled on the database, allowing recovery to any microsecond within the past 7 days.\n\n## Scheduled Exports\nA Cloud Function (or GCP Cloud Scheduler job) should be configured to run daily, exporting the entire \`turfs\`, \`users\`, and \`bookings\` collections to a secure Google Cloud Storage (GCS) Coldline bucket for long-term retention.`,

  '14-Backup-Recovery/Disaster Recovery.md': `# Disaster Recovery (DR)\n\n## Scenarios\n1. **Accidental Data Deletion (User Error):** If an admin accidentally purges a collection, PITR (if enabled) is utilized to revert the database state.\n2. **Vercel Outage:** In the rare event of a Vercel regional outage, the codebase is hosted on GitHub and can be rapidly deployed to an alternative provider (e.g., AWS Amplify or Netlify).\n3. **Firebase Outage:** PlaySphere relies heavily on GCP infrastructure. In a multi-region failure, the application will display a graceful maintenance page. Offline bookings cannot be processed during this window.`,

  '14-Backup-Recovery/Restore Process.md': `# Restore Process\n\n## Restoring from GCS Export\n1. Authenticate with the \`gcloud\` CLI using an account with \`Owner\` privileges on the GCP project.\n2. Execute the Firestore import command pointing to the specific backup timestamp bucket.\n\n\`\`\`bash\ngcloud firestore import gs://playsphere-backups/2024-12-01T00:00:00Z\n\`\`\`\n\n*Warning: Importing over existing documents will overwrite them. It is recommended to restore to a staging database first to verify data integrity.*`,

  '14-Backup-Recovery/Business Continuity.md': `# Business Continuity\n\nPlaySphere aims to ensure minimal disruption to Turf Owners' businesses during technical incidents.\n\n- **Offline PWA Capability:** If the client loses internet connection, the PWA will serve the cached app shell, allowing owners to view their cached ledger, even if they cannot sync new online bookings.\n- **Manual Fallback:** In a total platform outage, owners are instructed to revert to physical ledgers temporarily; post-outage, these can be manually entered into the system via the \"Offline Booking\" portal to reconcile the calendar.`,

  // 15-User-Guides
  '15-User-Guides/Player Manual.md': `# Player Manual\n\nWelcome to PlaySphere! Booking a turf is simple.\n\n1. **Sign Up/Login:** Use your Google account or email to create an account.\n2. **Find a Turf:** Use the homepage search bar to filter turfs by city and sport (e.g., \"Mumbai\", \"Football\").\n3. **Pick a Slot:** Click on a turf to view its details. Select an available green time slot on your preferred date.\n4. **Pay Securely:** Click \"Book Now\" and complete the payment via UPI, Card, or Netbanking.\n5. **Check-In:** You will receive a 4-digit OTP. Show this OTP to the turf manager when you arrive at the venue to check in!`,

  '15-User-Guides/Turf Owner Manual.md': `# Turf Owner Manual\n\nAs a Turf Owner, your dashboard is your central command center.\n\n## 1. Viewing Bookings\nNavigate to the **Bookings** tab to see a chronological list of all reservations. Use the filters to search by date or specific turf.\n\n## 2. Checking in a Player\nWhen a player arrives, ask for their 4-digit OTP. Enter it into the \"Quick Verify OTP\" field on your dashboard to mark them as arrived.\n\n## 3. Adding an Offline Booking (Walk-in)\nIf a customer calls or walks in, go to the **Add Offline Booking** tab. Select the turf, date, and slot, and enter their name. This immediately blocks the slot online so nobody else can book it.\n\n## 4. Processing Refunds\nIf a booking must be cancelled, find the booking in your list and change the status to **Refunded**. The money will be returned to the customer via Razorpay automatically (takes 5-7 days).`,

  '15-User-Guides/Admin Manual.md': `# Admin Manual\n\n## Super Admin Dashboard\nThe Admin Dashboard provides platform-wide oversight.\n\n- **Verification:** New turfs added by owners must be manually reviewed and marked as \`isActive = true\` via the database or admin panel before they appear in public search results.\n- **Disputes:** Admins have global read access to the \`audit_logs\` and \`payments\` collections to investigate disputed charges or double-booking claims.\n- **Metrics:** View global GMV (Gross Merchandise Value) and total user acquisition metrics.`,

  '15-User-Guides/FAQ.md': `# Frequently Asked Questions (FAQ)\n\n**Q: What happens if two people try to book the same slot at the exact same time?**\nA: PlaySphere uses Firestore's transactional \`create\` rules and backend verification to ensure that only the first successful payment secures the slot. The second user's payment will trigger a refund, and they will be notified that the slot was taken.\n\n**Q: How do I install the app on my phone?**\nA: Open PlaySphere in Chrome or Safari. A popup will appear at the bottom asking you to \"Install PlaySphere\". Click it, and the app will be added to your home screen.\n\n**Q: Are my payments secure?**\nA: Yes. PlaySphere does not store credit card details. All transactions are securely processed by Razorpay, an RBI-compliant gateway.`,

  '15-User-Guides/Troubleshooting.md': `# Troubleshooting\n\n**Issue: The booking slot is spinning and not loading.**\n*Fix:* Check your internet connection. If the issue persists, perform a hard refresh (Ctrl+Shift+R) to clear your browser cache.\n\n**Issue: I am a Turf Owner but my dashboard says \"0 Bookings\" even though I have reservations.**\n*Fix:* If you recently deployed the app, ensure the Firebase Composite Indexes have finished building in the Firebase Console. The dashboard cannot load data until the index is enabled.\n\n**Issue: Payment was deducted but booking failed.**\n*Fix:* The system will automatically reconcile this within 24 hours via Razorpay webhooks and issue an auto-refund. Contact support if the refund is not initiated.`,

  // 16-Operations
  '16-Operations/Release Notes.md': `# Release Notes\n\n## v1.0.0 (Current Production Release)\n- **Performance:** Migrated homepage and search to Next.js Server Components, eliminating client-side data waterfalls.\n- **Features:** Launched PWA Install prompt for seamless mobile installation.\n- **Security:** Hardened Firebase Security rules and shifted offline booking creation to a secure server API.\n- **Payments:** Integrated Razorpay checkout with HMAC server-side signature verification.\n- **Dashboard:** Deployed comprehensive Turf Owner dashboard with OTP check-in capability.`,

  '16-Operations/Changelog.md': `# Changelog\n\n## [1.0.0] - 2026-07-27\n### Added\n- Next.js 15 App Router architecture.\n- Firebase Authentication (Google/Email).\n- Razorpay Payment Gateway integration.\n- Progressive Web App (PWA) manifest and Service Worker.\n- Role-Based Access Control (RBAC).\n\n### Changed\n- Shifted \`getAllLocations\` and \`getSports\` queries to execute on the server for faster initial page loads.\n- Updated \`createOfflineBooking\` to utilize a deterministic document ID strategy (\`turfId_date_slot\`) to guarantee collision prevention.`,

  '16-Operations/Version History.md': `# Version History\n\n| Version | Release Date | Key Features |\n|---------|--------------|--------------|\n| 1.0.0   | 2026-07-27   | Initial MVP Launch: SSR Search, Razorpay Integration, Owner Dashboard, Offline Bookings, PWA. |\n| 0.9.0   | 2026-06-15   | Beta Testing: Core Firebase integration, Client-side routing. |`,

  '16-Operations/Known Limitations.md': `# Known Limitations\n\n1. **Razorpay Webhooks:** While signature verification is robust, asynchronous webhooks for \`payment.captured\` are not yet implemented, meaning users who close their browser prematurely during checkout might face manual reconciliation.\n2. **Dynamic Slot Generation:** The booking form currently relies on a static array of time slots (e.g., 06:00 to 22:00) rather than dynamically reading the specific turf's \`operatingHours\`.\n3. **Pagination:** The Turf Search page fetches all active turfs at once. While acceptable for the current scale, cursor-based pagination is required as the database grows to thousands of venues.`,

  '16-Operations/Future Roadmap.md': `# Future Roadmap\n\n1. **Razorpay Route (Split Payments):** Automate payouts directly to Turf Owners' bank accounts at the time of booking, taking only the platform commission.\n2. **WhatsApp API Integration:** Send instant booking confirmations and OTPs directly to players' WhatsApp numbers via Twilio or Meta API.\n3. **Dynamic Pricing Engine:** Allow owners to set higher prices for peak hours (e.g., 7 PM - 10 PM) or weekends automatically.\n4. **Subscription Models:** Implement a SaaS payment tier allowing owners to unlock advanced analytics and SMS features for a monthly fee.\n5. **Review System:** Launch the \`reviews\` collection to allow players to rate turfs out of 5 stars, influencing search ranking.`,

  // 17-Legal
  '17-Legal/License.md': `# License\n\nCopyright (c) 2026 PlaySphere.\n\nAll rights reserved. The source code, design, and architecture contained within this repository are proprietary and confidential. Unauthorized copying, distribution, or modification of this software, via any medium, is strictly prohibited without explicit written permission from the PlaySphere administration.`,

  '17-Legal/Privacy Policy.md': `# Privacy Policy\n\nPlaySphere is committed to protecting your privacy.\n\n## 1. Data Collection\nWe collect personal information including your name, email address, phone number, and booking history when you register and interact with our platform.\n\n## 2. Data Usage\nYour data is used exclusively to facilitate turf bookings, process secure payments, and communicate crucial transactional information (e.g., OTPs). \n\n## 3. Data Sharing\nWe share your name and phone number strictly with the owner of the turf you have booked to facilitate your physical check-in. We do NOT sell your data to third-party marketers.\n\n## 4. Payment Data\nPlaySphere does not collect, store, or process your credit card or bank details. All financial transactions are securely handled by our PCI-DSS compliant partner, Razorpay.`,

  '17-Legal/Terms & Conditions.md': `# Terms & Conditions\n\nBy accessing PlaySphere, you agree to be bound by these terms.\n\n## 1. User Responsibilities\nPlayers must arrive at the venue on time. PlaySphere is not responsible for time lost due to late arrivals. Turf Owners are responsible for maintaining the physical quality of the facility as advertised.\n\n## 2. Platform Liability\nPlaySphere acts as an intermediary technology platform. Any physical injuries sustained at a venue, or disputes arising from venue quality, must be resolved directly between the Player and the Turf Owner.\n\n## 3. Account Termination\nPlaySphere reserves the right to suspend any Player or Turf Owner account found violating these terms, engaging in fraudulent payments, or repeatedly bypassing platform guidelines.`,

  '17-Legal/Refund Policy.md': `# Refund Policy\n\n## Platform Refunds\nRefunds are strictly governed by the cancellation timeframe relative to the booked slot.\n\n1. **Initiation:** Refunds are processed back to the original payment method (UPI, Card, Bank Account) via Razorpay.\n2. **Processing Time:** Once initiated, refunds typically take 5 to 7 business days to reflect in the customer's account depending on the issuing bank.\n3. **Platform Fees:** Convenience fees or platform commissions may be non-refundable depending on the specific transaction terms.`,

  '17-Legal/Cancellation Policy.md': `# Cancellation Policy\n\n## 1. Player Cancellations\n- Cancellations made more than 24 hours prior to the booked slot are eligible for a full refund (excluding gateway charges).\n- Cancellations made within 12-24 hours may be subject to a 50% cancellation fee.\n- Cancellations made less than 12 hours before the slot are strictly non-refundable.\n\n## 2. Owner Cancellations\nIf a Turf Owner cancels a confirmed booking (due to maintenance, weather, or emergency), the Player will receive a 100% full refund automatically initiated by the platform.`,

  // 18-Contributors
  '18-Contributors/Team.md': `# Team\n\nThe PlaySphere platform was conceptualized, designed, and engineered to bridge the gap in the recreational sports industry.\n\n## Core Roles\n- **Founding Team:** Responsible for business strategy, turf onboarding, and platform vision.\n- **Engineering:** Responsible for the full-stack architecture (Next.js, Firebase), payment integration, and performance optimization.\n- **Operations:** Responsible for customer support, dispute resolution, and managing turf owner relations.`,

  '18-Contributors/Roles & Responsibilities.md': `# Roles & Responsibilities\n\n## Engineering Team\n- Architecture design and maintenance.\n- Ensuring PCI-DSS and data privacy compliance.\n- Uptime monitoring and incident response.\n\n## Product Management\n- Roadmap prioritization (e.g., WhatsApp integration, Subscription tiers).\n- User Experience (UX) auditing and feature definition.\n\n## Sales & Onboarding\n- Physically verifying turf facilities before granting \"Active\" status on the platform.\n- Training Turf Owners on utilizing the Admin Dashboard and Offline Booking system.`,

  '18-Contributors/Acknowledgements.md': `# Acknowledgements\n\nPlaySphere relies on the incredible work of the open-source community and our technology partners:\n\n- **Vercel & Next.js:** For providing a world-class edge rendering framework.\n- **Google Firebase:** For the massively scalable NoSQL infrastructure and identity management.\n- **Razorpay:** For democratizing secure digital payments in India.\n- **Shadcn UI & Tailwind CSS:** For the beautiful, accessible, and highly customizable component primitives that make up the PlaySphere interface.\n- **Lucide Icons:** For the comprehensive and clean iconography.`,

  // 19-Appendices
  '19-Appendices/Glossary.md': `# Glossary\n\n- **Turf:** An artificial grass sports facility, typically used for football or box cricket.\n- **Slot:** A specific 60-minute time block available for booking at a turf (e.g., 18:00 - 19:00).\n- **Offline Booking:** A reservation made by a customer via phone call or walk-in, which the Turf Owner manually inputs into the dashboard to block the slot.\n- **Check-In:** The process of verifying a player's arrival at the venue using a 4-digit OTP generated by the platform.\n- **Admin SDK:** A privileged backend library used to bypass client security rules for secure operations.`,

  '19-Appendices/Acronyms.md': `# Acronyms\n\n- **PWA:** Progressive Web App\n- **SSR:** Server-Side Rendering\n- **CSR:** Client-Side Rendering\n- **RSC:** React Server Components\n- **API:** Application Programming Interface\n- **RBAC:** Role-Based Access Control\n- **OTP:** One-Time Password\n- **JWT:** JSON Web Token\n- **HMAC:** Hash-based Message Authentication Code\n- **UX / UI:** User Experience / User Interface\n- **GMV:** Gross Merchandise Value\n- **SEO:** Search Engine Optimization`,

  '19-Appendices/Coding Standards.md': `# Coding Standards\n\n## TypeScript\n- \`any\` types are heavily discouraged. Strict interfaces must be defined in the \`types/\` directory for all Firestore data models.\n- Functional components with React Hooks are the standard; Class components are prohibited.\n\n## Styling\n- All styling must use Tailwind CSS utility classes.\n- Complex conditional class merging must use the \`cn()\` utility function (combining \`clsx\` and \`tailwind-merge\`) located in \`lib/utils.ts\`.\n\n## Data Fetching\n- Public data (Homepage, Search) must be fetched Server-Side inside \`page.tsx\` components.\n- Private data (Dashboards) should be fetched Client-Side utilizing \`useEffect\` or SWR/React Query for persistent sessions.`,

  '19-Appendices/Git Workflow.md': `# Git Workflow\n\nPlaySphere follows a trunk-based development workflow.\n\n## Branch Naming\n- \`feat/short-description\` (e.g., \`feat/whatsapp-integration\`)\n- \`fix/short-description\` (e.g., \`fix/payment-signature-bug\`)\n- \`chore/short-description\` (e.g., \`chore/update-dependencies\`)\n\n## Process\n1. Branch off \`main\`.\n2. Commit frequently with descriptive messages.\n3. Push to GitHub to trigger a Vercel Preview Deployment.\n4. Review the preview URL.\n5. Merge via Pull Request into \`main\` to trigger the Production Deployment.`,

  '19-Appendices/Naming Conventions.md': `# Naming Conventions\n\n## Files and Directories\n- **React Components:** PascalCase (e.g., \`BookingModal.tsx\`, \`TurfCard.tsx\`).\n- **Utility/Service Files:** camelCase (e.g., \`booking.service.ts\`, \`firebase-admin.ts\`).\n- **Next.js App Router:** Reserved filenames must be strictly lowercase (e.g., \`page.tsx\`, \`layout.tsx\`, \`route.ts\`).\n\n## Variables and Functions\n- **Variables:** camelCase (e.g., \`selectedTurfId\`, \`isSubmitting\`).\n- **Booleans:** Prefix with \`is\`, \`has\`, or \`should\` (e.g., \`isOffline\`, \`hasVerifiedOtp\`).\n- **Constants/Env Vars:** UPPER_SNAKE_CASE (e.g., \`RAZORPAY_KEY_SECRET\`).\n- **Components:** PascalCase (e.g., \`<PaymentForm />\`).`,

  '19-Appendices/References.md': `# References\n\n## Official Documentation\n- **Next.js:** [https://nextjs.org/docs](https://nextjs.org/docs)\n- **Firebase Auth:** [https://firebase.google.com/docs/auth](https://firebase.google.com/docs/auth)\n- **Firestore:** [https://firebase.google.com/docs/firestore](https://firebase.google.com/docs/firestore)\n- **Razorpay Node SDK:** [https://github.com/razorpay/razorpay-node](https://github.com/razorpay/razorpay-node)\n- **Tailwind CSS:** [https://tailwindcss.com/docs](https://tailwindcss.com/docs)\n- **Shadcn UI:** [https://ui.shadcn.com/docs](https://ui.shadcn.com/docs)`,

  '19-Appendices/Project Timeline.md': `# Project Timeline\n\n## Phase 1: MVP Development (Completed)\n- Architecture setup, Firebase integration.\n- PWA configuration, Razorpay checkout.\n- Turf Owner dashboard and offline booking system.\n\n## Phase 2: Optimization (Completed)\n- Migration of public routes to Next.js Server Components.\n- Implementation of Firebase Admin SDK for secure offline operations.\n- Resolution of complex Firestore Composite Index requirements.\n\n## Phase 3: Scaling & Growth (Upcoming)\n- Integration of WhatsApp messaging for automated alerts.\n- Implementation of dynamic pricing models based on slot demand.\n- Automated Razorpay Route payouts for seamless owner settlements.\n- Rollout of the comprehensive Super Admin analytics suite.`
};

for (const [relPath, content] of Object.entries(docs)) {
  const fullPath = path.join(rootDir, relPath);
  fs.writeFileSync(fullPath, content, 'utf8');
}
console.log('Successfully generated batch 5.');
