const fs = require('fs');
const path = require('path');

const rootDir = 'c:/Users/Lenovo/Downloads/playsphere-main-main/playsphere-main-main/PlaySphere-Documentation';

const docs = {
  // 05-API
  '05-API/API Overview.md': `# API Overview\n\nPlaySphere uses a hybrid API architecture. The primary data interface for client applications is the Firebase Client SDK (Firestore and Auth), which handles direct reads and writes governed by Firestore Security Rules. \n\nFor privileged operations that must bypass client rules (e.g., payments, offline booking creation), PlaySphere exposes custom Serverless API routes built on the Next.js App Router (\`/api/*\`). These routes leverage the Firebase Admin SDK.\n\n## Base URL\nIn development: \`http://localhost:3000/api\`\nIn production: \`https://your-domain.com/api\`\n\n## Global Headers\nAll custom API routes that mutate data expect JSON payloads.\n\`\`\`http\nContent-Type: application/json\n\`\`\``,

  '05-API/Authentication APIs.md': `# Authentication APIs\n\nPlaySphere primarily uses the Firebase Authentication Client SDK for user management. There are no custom \`/api/auth\` Next.js endpoints exposed, as session states and tokens are managed directly between the browser and Google's Firebase servers.\n\n## Client Operations\n- **Login:** \`signInWithEmailAndPassword\`, \`signInWithPopup\` (Google)\n- **Logout:** \`signOut\`\n- **Token:** \`getIdToken\` (used if calling secure custom endpoints in the future)\n\n## Server Validation\nIn the Next.js Server Components, authentication state is evaluated based on Firebase constraints, although currently, most access control is managed client-side via React Context and Route Guards.`,

  '05-API/User APIs.md': `# User APIs\n\nUser profiles are managed entirely via Firebase Client SDKs pointing to the \`users\` Firestore collection.\n\n## Client SDK Operations\n\n### Fetch User Profile\n\`\`\`javascript\nconst docRef = doc(db, 'users', uid);\nconst docSnap = await getDoc(docRef);\n\`\`\`\n\n### Update User Profile\n\`\`\`javascript\nconst docRef = doc(db, 'users', uid);\nawait updateDoc(docRef, { name: 'New Name', phone: '1234567890' });\n\`\`\`\n*Note: Firestore rules strictly prohibit a user from updating their \`role\` field.*`,

  '05-API/Turf APIs.md': `# Turf APIs\n\nTurf data is accessed via the Firebase Client SDK against the \`turfs\` collection.\n\n## Client SDK Operations\n\n### Fetch All Turfs (Players)\n\`\`\`javascript\nconst q = query(collection(db, 'turfs'), where('isActive', '==', true));\nconst snapshot = await getDocs(q);\n\`\`\`\n\n### Fetch Owner Turfs (Owners)\n\`\`\`javascript\nconst q = query(collection(db, 'turfs'), where('ownerId', '==', currentUser.uid));\nconst snapshot = await getDocs(q);\n\`\`\``,

  '05-API/Booking APIs.md': `# Booking APIs\n\nBooking operations utilize a mix of Client SDKs (for reads and standard creation) and Serverless APIs (for privileged offline booking creation).\n\n## Serverless Endpoint: Create Offline Booking\n\n**Endpoint:** \`/api/booking/offline\`\n**Method:** \`POST\`\n**Description:** Creates a confirmed booking bypassing client security rules. Deterministically blocks overlapping slots.\n\n### Request Payload\n\`\`\`json\n{\n  \"turfId\": \"string\",\n  \"date\": \"YYYY-MM-DD\",\n  \"slot\": \"HH:MM\",\n  \"ownerId\": \"string\",\n  \"playerName\": \"string\",\n  \"mobile\": \"string\",\n  \"source\": \"string (Walk-in | Phone Call)\",\n  \"paymentMethod\": \"string (Cash | UPI)\"\n}\n\`\`\`\n\n### Response (Success 200 OK)\n\`\`\`json\n{\n  \"success\": true,\n  \"id\": \"string (deterministic ID)\"\n}\n\`\`\`\n\n### Response (Conflict 409)\n\`\`\`json\n{\n  \"success\": false,\n  \"message\": \"This slot is already booked.\"\n}\n\`\`\``,

  '05-API/Payment APIs.md': `# Payment APIs\n\nPayment APIs interface with Razorpay and secure the transaction flow.\n\n## 1. Create Razorpay Order\n**Endpoint:** \`/api/payment/create-order\`\n**Method:** \`POST\`\n**Description:** Generates a secure \`razorpay_order_id\` for checkout.\n\n### Request\n\`\`\`json\n{ \"amount\": 1500 }\n\`\`\`\n### Response\n\`\`\`json\n{ \"orderId\": \"order_abc123\" }\n\`\`\`\n\n## 2. Verify Payment Signature\n**Endpoint:** \`/api/payment/verify\`\n**Method:** \`POST\`\n**Description:** Verifies the cryptographic HMAC signature returned by Razorpay and commits the booking to Firestore.\n\n### Request\n\`\`\`json\n{\n  \"razorpay_order_id\": \"string\",\n  \"razorpay_payment_id\": \"string\",\n  \"razorpay_signature\": \"string\",\n  \"bookingData\": { /* Booking Details */ }\n}\n\`\`\`\n### Response\n\`\`\`json\n{ \"success\": true, \"bookingId\": \"string\" }\n\`\`\`\n\n## 3. Process Refund\n**Endpoint:** \`/api/payment/refund\`\n**Method:** \`POST\`\n**Description:** Issues a full refund via Razorpay for a cancelled booking.\n\n### Request\n\`\`\`json\n{ \"bookingId\": \"string\", \"adminUid\": \"string\" }\n\`\`\``,

  '05-API/Admin APIs.md': `# Admin APIs\n\nCurrently, administrative dashboards read global collections using the Firebase Client SDK under elevated Firebase Security Rules (where \`role == 'admin'\`).\n\nGlobal statistics (e.g., total users, total revenue) are calculated using client-side aggregations, though future roadmap items suggest moving these to dedicated Next.js Server Components or Cloud Functions to reduce document read costs.`,

  '05-API/Error Codes.md': `# Error Codes\n\nPlaySphere APIs use standard HTTP status codes combined with JSON error messages.\n\n## HTTP Status Codes\n- **200 OK:** Request succeeded.\n- **400 Bad Request:** Missing or malformed parameters (e.g., missing \`turfId\`).\n- **401 Unauthorized:** Missing or invalid authentication.\n- **403 Forbidden:** Authenticated user lacks privileges (e.g., non-owner attempting refund).\n- **409 Conflict:** Resource state conflict (e.g., Slot already booked).\n- **500 Internal Server Error:** Unexpected backend exception.\n\n## Standard Error Response Format\n\`\`\`json\n{\n  \"success\": false,\n  \"message\": \"Human-readable error description\"\n}\n\`\`\``,

  '05-API/API Examples.md': `# API Examples\n\n## Example: Verifying a Payment via cURL\n\n\`\`\`bash\ncurl -X POST https://api.playsphere.com/api/payment/verify \\\n  -H \"Content-Type: application/json\" \\\n  -d '{\n    \"razorpay_order_id\": \"order_Pf7abc...\",\n    \"razorpay_payment_id\": \"pay_Pf7def...\",\n    \"razorpay_signature\": \"a1b2c3d4e5f6...\",\n    \"bookingData\": {\n      \"turfId\": \"turf_123\",\n      \"date\": \"2024-12-01\",\n      \"slot\": \"18:00\"\n    }\n  }'\n\`\`\`\n\n## Example: Fetching Owner Bookings (Client SDK)\n\`\`\`javascript\nimport { collection, query, where, orderBy, getDocs } from 'firebase/firestore';\n\nconst fetchBookings = async (ownerId) => {\n  const q = query(\n    collection(db, 'bookings'),\n    where('ownerId', '==', ownerId),\n    orderBy('createdAt', 'desc')\n  );\n  const snapshot = await getDocs(q);\n  return snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() }));\n};\n\`\`\``,

  // 06-Authentication
  '06-Authentication/Firebase Authentication.md': `# Firebase Authentication\n\nPlaySphere delegates identity management completely to Google's Firebase Authentication service. This ensures enterprise-grade security for user credentials without the platform storing plain-text passwords or maintaining session cookies manually.\n\n## Supported Providers\n- **Email and Password:** Standard registration/login flow.\n- **Google OAuth (SSO):** One-click sign-in leveraging Google accounts.\n\n## Lifecycle\nWhen a user registers, an authentication record is created in Firebase Auth. A corresponding profile document is subsequently created in the Firestore \`users\` collection to store metadata and application-specific roles (\`player\`, \`owner\`, \`admin\`).`,

  '06-Authentication/Login Flow.md': `# Login Flow\n\n## 1. Credential Submission\nThe user submits credentials via the login form, which are passed to the Firebase Auth SDK (\`signInWithEmailAndPassword\`).\n\n## 2. Token Generation\nFirebase authenticates the user and returns an ID Token containing the user's UUID (uid).\n\n## 3. Profile Fetch\nThe application's React \`AuthContext\` listens to the \`onAuthStateChanged\` event. Upon detecting a login, it immediately fetches the corresponding document from the Firestore \`users\` collection.\n\n## 4. Redirection\nBased on the \`role\` defined in the fetched profile document, the user is redirected:\n- **Player:** Redirected to \`/\` (Home/Search).\n- **Owner:** Redirected to \`/owner/dashboard\`.\n- **Admin:** Redirected to \`/admin/dashboard\`.`,

  '06-Authentication/RBAC.md': `# Role-Based Access Control (RBAC)\n\nPlaySphere enforces authorization via three core roles defined in the Firestore \`users\` collection.\n\n## Roles\n1. **Player (Default):** \n   - Can browse active turfs.\n   - Can create online bookings.\n   - Can view only their own bookings.\n2. **Owner:**\n   - Can create, edit, and manage their own turfs.\n   - Can view bookings associated with their \`ownerId\`.\n   - Can create offline bookings for their turfs.\n3. **Admin (Super Admin):**\n   - Can view all users, turfs, and bookings platform-wide.\n   - Can suspend/approve turfs and resolve disputes.\n\n## Enforcement\n- **Client Side:** React Route Guards prevent UI access to unauthorized pages.\n- **Database Side:** Firestore Security Rules actively block read/write operations if the user's role does not match the required privileges.`,

  '06-Authentication/Protected Routes.md': `# Protected Routes\n\nPlaySphere implements Route Guards using React Higher-Order Components or layout wrappers to restrict access to sensitive pages.\n\n## Implementation Mechanism\nThe \`AuthContext\` provides the current user's state and role. If a user navigates to a protected route (e.g., \`/owner/dashboard\`) without the \`owner\` role, the client-side router immediately intercepts the request and redirects them to the login page or a "Forbidden" page.\n\n## Route Mappings\n- \`/owner/*\` -> Requires Authentication + \`role == 'owner'\`\n- \`/admin/*\` -> Requires Authentication + \`role == 'admin'\`\n- \`/profile\` -> Requires Authentication (Any role)`,

  '06-Authentication/Session Management.md': `# Session Management\n\n## Token Lifecycle\nFirebase Authentication handles session persistence automatically in the browser using IndexedDB/LocalStorage. \n- The Firebase SDK refreshes the JWT ID token automatically every hour in the background.\n- The \`AuthContext\` ensures the UI is synchronized with the session state.\n\n## Security Context\nBecause Next.js Server Components (SSR) cannot directly read IndexedDB, sensitive pages relying heavily on SSR might experience a flash of unauthenticated state or require client-side data fetching. PlaySphere utilizes client-side rendering (CSR) for highly dynamic, authenticated dashboards (like the Owner Dashboard) to leverage the Firebase Client SDK's persistent session seamlessly.`,

  // 07-Payments
  '07-Payments/Razorpay Integration.md': `# Razorpay Integration\n\nPlaySphere utilizes Razorpay as the exclusive payment gateway to handle all online booking transactions. Razorpay ensures PCI-DSS compliance, abstracting credit card and UPI handling away from the PlaySphere application servers.\n\n## Component Roles\n- **Client:** Uses the Razorpay Checkout script (\`https://checkout.razorpay.com/v1/checkout.js\`) to display the payment modal.\n- **Server:** Secures the transaction by generating orders and verifying signatures using the \`razorpay\` Node.js SDK.`,

  '07-Payments/Payment Flow.md': `# Payment Flow\n\n## Step-by-Step Transaction Lifecycle\n\n1. **Initialization:** The player selects a slot and clicks "Book".\n2. **Order Creation:** The client POSTs to \`/api/payment/create-order\`. The Next.js server calls Razorpay to generate a unique \`order_id\` for the specified amount.\n3. **Checkout UI:** The client initializes the Razorpay Checkout modal with the returned \`order_id\`, Turf Name, and User details.\n4. **Payment Processing:** The player completes the payment (via UPI, Card, Netbanking) inside the Razorpay UI.\n5. **Callback:** Razorpay returns the \`razorpay_payment_id\`, \`razorpay_order_id\`, and \`razorpay_signature\` to the client.\n6. **Verification:** The client forwards these parameters, alongside the booking data, to \`/api/payment/verify\`.\n7. **Confirmation:** The server verifies the HMAC SHA256 signature using the \`RAZORPAY_KEY_SECRET\`. If valid, it writes the booking to Firestore and responds with a success status.\n8. **Check-in:** The client displays a 4-digit OTP to the user for physical venue check-in.`,

  '07-Payments/Webhooks.md': `# Webhooks\n\n> **Note:** The current architecture relies primarily on synchronous client-to-server signature verification (\`/api/payment/verify\`). Implementing Razorpay Webhooks (e.g., \`/api/webhooks/razorpay\`) is recommended for the future roadmap to handle edge cases.\n\n## Future Webhook Implementation\nWebhooks should be implemented to capture asynchronous payment events, particularly:\n- \`payment.captured\`: To confirm bookings if the user's browser closes before the client callback executes.\n- \`refund.processed\`: To update the Firestore booking status when a refund clears through the banking network.`,

  '07-Payments/Settlement.md': `# Settlement\n\n## Standard Flow\nPayments collected via Razorpay are deposited into the central PlaySphere Razorpay merchant account. \n\n## Current Operation\nSettlements to individual Turf Owners are currently managed manually outside the platform via standard bank transfers (NEFT/RTGS), calculated using the revenue metrics provided in the Admin Dashboard.\n\n## Future Roadmap (Razorpay Route)\nImplementing Razorpay Route will allow PlaySphere to automatically split transactions at the time of booking, routing the owner's share directly to their linked bank account while retaining the platform's commission in the primary account.`,

  '07-Payments/Refund Flow.md': `# Refund Flow\n\nPlaySphere provides a secure, server-side refund mechanism for cancelled bookings.\n\n## Execution Flow\n1. A Turf Owner (or Admin) initiates a refund via the dashboard UI.\n2. A POST request is sent to \`/api/payment/refund\` containing the \`bookingId\`.\n3. The server validates the requestor's authorization (must be the owner of the turf or an admin).\n4. The server fetches the \`paymentId\` from the booking record.\n5. The server issues a \`razorpay.payments.refund()\` API call.\n6. Upon success, the server updates the booking status in Firestore to \`refunded\`.\n\n*Note: Refunds typically take 5-7 business days to reflect in the customer's account depending on the payment method.*`,

  '07-Payments/Payment Security.md': `# Payment Security\n\n## Signature Verification\nPlaySphere strictly adheres to Razorpay's security guidelines. No booking is created in Firestore until the payment signature is cryptographically verified on the server.\n\n\`\`\`javascript\n// Verification Logic Representation\nconst crypto = require('crypto');\nconst expectedSignature = crypto\n  .createHmac('sha256', process.env.RAZORPAY_KEY_SECRET)\n  .update(razorpay_order_id + '|' + razorpay_payment_id)\n  .digest('hex');\n\nif (expectedSignature === razorpay_signature) {\n  // Payment is authentic\n}\n\`\`\`\n\n## Protection Against Forgery\nBecause the \`RAZORPAY_KEY_SECRET\` is stored securely in Vercel environment variables and never exposed to the client, it is computationally impossible for a malicious actor to forge a valid signature to bypass payment and create a free booking.`,

  // 08-PWA
  '08-PWA/PWA Overview.md': `# PWA Overview\n\nPlaySphere is implemented as a Progressive Web App (PWA). This ensures the application can be installed on users' mobile devices directly from the browser (bypassing App Stores), providing a native-app-like experience, push notification capabilities, and improved performance through aggressive caching.\n\n## Core Technologies\n- **next-pwa:** A Next.js plugin that handles the automatic generation of Service Workers and Workbox configuration during the build process.\n- **Web App Manifest:** Provides the OS with metadata (icons, name, theme colors) required for installation.\n\n## User Experience\nUsers visiting PlaySphere on supported browsers (Chrome, Safari, Edge) are presented with a custom, persistent "Install App" prompt. Upon installation, PlaySphere appears on their home screen and launches in a standalone, immersive window without browser chrome.`,

  '08-PWA/Manifest.md': `# Manifest (manifest.json)\n\nThe Web App Manifest is a JSON file that tells the browser how PlaySphere should behave when installed on the user's desktop or mobile device.\n\n## Configuration Snapshot\n\`\`\`json\n{\n  \"name\": \"PlaySphere\",\n  \"short_name\": \"PlaySphere\",\n  \"description\": \"Book sports turfs instantly.\",\n  \"start_url\": \"/\",\n  \"display\": \"standalone\",\n  \"background_color\": \"#000000\",\n  \"theme_color\": \"#84cc16\",\n  \"orientation\": \"portrait\",\n  \"icons\": [\n    {\n      \"src\": \"/icons/icon-192x192.png\",\n      \"sizes\": \"192x192\",\n      \"type\": \"image/png\"\n    },\n    {\n      \"src\": \"/icons/icon-512x512.png\",\n      \"sizes\": \"512x512\",\n      \"type\": \"image/png\"\n    }\n  ]\n}\n\`\`\``,

  '08-PWA/Service Workers.md': `# Service Workers\n\nPlaySphere utilizes an auto-generated Service Worker (via \`next-pwa\`) named \`sw.js\`. \n\n## Responsibilities\n- **Interception:** The Service Worker acts as a network proxy, intercepting outgoing requests from the browser.\n- **Caching:** It serves static assets (HTML, CSS, JS, Images) from the local cache to drastically reduce load times on subsequent visits.\n- **Update Management:** The \`PWARegister\` component listens for Service Worker updates. When a new version of PlaySphere is deployed, the UI prompts the user with a "New version available! Update Now" banner, which forces the Service Worker to skip waiting and reload the application.`,

  '08-PWA/Offline Support.md': `# Offline Support\n\n## App Shell Caching\nThe PWA caches the application shell (the UI layout, fonts, and core JavaScript) locally. If a user opens PlaySphere without an internet connection, the UI will load immediately rather than displaying the browser's default "No Internet" dinosaur page.\n\n## Data Resilience\nFirebase Firestore provides robust offline persistence out-of-the-box. \n- If a user loses connection while navigating the app, Firestore serves previously fetched data (like their profile or recent bookings) from its local IndexedDB cache.\n- *Note: Creating new bookings requires an active network connection to process the Razorpay transaction.*`,

  '08-PWA/Push Notifications.md': `# Push Notifications\n\n> **Note:** Based on the current codebase analysis, Web Push Notifications are not yet fully implemented. It is documented here as a recommendation for the future roadmap.\n\n## Future Implementation Strategy\n1. **FCM Integration:** Utilize Firebase Cloud Messaging (FCM) to request notification permissions from the user via the browser API.\n2. **Token Storage:** Save the FCM device token to the user's profile in Firestore.\n3. **Server Triggers:** Configure Cloud Functions or Next.js APIs to trigger FCM payloads (e.g., "Booking Confirmed", "Slot Reminder") to the specific device token.\n4. **Service Worker Handling:** The \`sw.js\` file will capture incoming push events and display native OS-level notifications to the user.`,

  '08-PWA/Caching Strategy.md': `# Caching Strategy\n\nPlaySphere employs a hybrid caching strategy generated by \`next-pwa\` and Workbox.\n\n## Strategies Employed\n1. **Cache First (Static Assets):** Images, fonts, and Next.js bundled JavaScript chunks are served directly from the cache to ensure maximum speed. The network is only queried if the asset is missing.\n2. **Network First (Dynamic Data):** For API requests (if cached) or HTML document requests, the Service Worker attempts to fetch the latest version from the network. If the network fails, it falls back to the last cached version.\n3. **Stale-While-Revalidate:** For less critical assets, the cache serves the asset instantly while simultaneously querying the network in the background to update the cache for the next visit.`,

  '08-PWA/Installation Guide.md': `# Installation Guide (For Users)\n\nPlaySphere offers a seamless installation process utilizing a custom, persistent UI prompt.\n\n## Installation Flow\n1. **Detection:** When a user visits PlaySphere on a supported browser, the browser fires the \`beforeinstallprompt\` event.\n2. **Capture:** The \`PWARegister\` component intercepts this event, preventing the default browser behavior.\n3. **Prompt:** A custom "Install PlaySphere" popup slides into view at the bottom left of the screen.\n4. **Action:** The user clicks "Install".\n5. **Completion:** The OS prompts for confirmation, and PlaySphere is added to the home screen/app drawer as a standalone application.`
};

for (const [relPath, content] of Object.entries(docs)) {
  const fullPath = path.join(rootDir, relPath);
  fs.writeFileSync(fullPath, content, 'utf8');
}
console.log('Successfully generated batch 3.');
