const fs = require('fs');
const path = require('path');

const rootDir = 'c:/Users/Lenovo/Downloads/playsphere-main-main/playsphere-main-main/PlaySphere-Documentation';

const docs = {
  // 09-Security
  '09-Security/Security Architecture.md': `# Security Architecture\n\nPlaySphere employs a defense-in-depth security architecture designed to protect sensitive user data, financial transactions, and internal administrative functions.\n\n## Core Security Pillars\n1. **Authentication & Identity:** Handled entirely by Google Firebase Auth (JWT-based).\n2. **Authorization (Data Level):** Enforced by Firestore Security Rules ensuring users can only read/write their authorized datasets.\n3. **Privileged Execution:** Serverless APIs (Next.js Edge/Node) utilizing the Firebase Admin SDK to bypass client rules securely.\n4. **Transport Layer:** 100% forced HTTPS/TLS 1.2+ for all data in transit.\n5. **Secret Management:** Hardened environment variables via Vercel preventing key leakage to the frontend bundle.`,

  '09-Security/Firestore Rules.md': `# Firestore Rules\n\nFirestore Security Rules act as the primary firewall for PlaySphere's data layer.\n\n## Rule Principles\n- **Default Deny:** All collections are closed by default.\n- **Ownership Verification:** Users can only mutate documents where \`request.auth.uid == resource.data.userId\` (or \`ownerId\`).\n- **Role Checks:** Write operations on global collections require the user's \`users\` document to possess \`role == 'admin'\`.\n\n## Example Rule Snippet\n\`\`\`javascript\nservice cloud.firestore {\n  match /databases/{database}/documents {\n    match /users/{userId} {\n      // Users can read/write their own profile\n      allow read, write: if request.auth != null && request.auth.uid == userId;\n    }\n    match /turfs/{turfId} {\n      // Anyone can read active turfs, only owners can write\n      allow read: if resource.data.isActive == true || \n                     (request.auth != null && request.auth.uid == resource.data.ownerId);\n      allow write: if request.auth != null && request.auth.uid == request.resource.data.ownerId;\n    }\n  }\n}\n\`\`\``,

  '09-Security/Input Validation.md': `# Input Validation\n\nPlaySphere validates input at both the client and server levels to prevent malformed data injection.\n\n## Client-Side Validation\n- Handled via controlled React components and HTML5 form constraints.\n- Prevents basic UI errors and reduces unnecessary API calls.\n\n## Server-Side Validation\n- All custom \`/api/*\` routes strictly parse and validate incoming JSON payloads.\n- If a required field (e.g., \`turfId\`, \`date\`, \`slot\`) is missing or malformed, the API immediately returns a \`400 Bad Request\`.\n\n> **Roadmap Recommendation:** Implement Zod or Yup schema validation in Next.js API routes for stricter type casting and automated error messaging.`,

  '09-Security/HTTPS.md': `# HTTPS\n\nPlaySphere enforces HTTPS across all endpoints.\n\n- **Vercel Enforcement:** Vercel automatically provisions SSL/TLS certificates (via Let's Encrypt) and redirects all \`http://\` traffic to \`https://\` with a 308 Permanent Redirect.\n- **Firebase APIs:** All Firebase client and Admin SDK communications natively occur over encrypted TLS connections.\n- **Razorpay:** Transaction payloads and webhooks are strictly transmitted over HTTPS.`,

  '09-Security/XSS & CSRF.md': `# XSS & CSRF\n\n## Cross-Site Scripting (XSS)\n- **React Safeguards:** React inherently protects against XSS by automatically escaping string variables in JSX before rendering them to the DOM.\n- **Dangerous HTML:** The \`dangerouslySetInnerHTML\` attribute is strictly avoided across the codebase.\n\n## Cross-Site Request Forgery (CSRF)\n- **Stateless APIs:** PlaySphere uses stateless JWTs (via Firebase Auth) instead of cookie-based sessions for custom API routes, inherently mitigating standard CSRF attack vectors.\n- **Next.js Protections:** Next.js Server Actions and API routes deployed on Vercel incorporate built-in origin checking.`,

  '09-Security/Secrets Management.md': `# Secrets Management\n\nProper handling of secrets is critical to preventing infrastructure compromise.\n\n## Exposed (Public) Keys\nVariables prefixed with \`NEXT_PUBLIC_\` are bundled into the client-side JavaScript. These are inherently safe to expose:\n- \`NEXT_PUBLIC_FIREBASE_API_KEY\`\n- \`NEXT_PUBLIC_RAZORPAY_KEY_ID\`\n\n## Confidential (Private) Keys\nThese variables are NEVER prefixed with \`NEXT_PUBLIC_\` and exist only in the Node.js server environment:\n- \`FIREBASE_PRIVATE_KEY\`\n- \`RAZORPAY_KEY_SECRET\`\n\n## Injection\nIn production, all secrets are securely injected into the Vercel Build and Runtime environments via the Vercel Dashboard. They are never committed to the Git repository.`,

  '09-Security/OWASP Checklist.md': `# OWASP Checklist\n\nPlaySphere aligns with the OWASP Top 10 security guidelines:\n\n1. **Broken Access Control:** Mitigated via Firestore Rules and Next.js Route Guards.\n2. **Cryptographic Failures:** Mitigated by forced HTTPS and Razorpay HMAC SHA256 signatures.\n3. **Injection (SQL/NoSQL):** Mitigated by Firebase SDK parameterization (NoSQL injection is inherently difficult in Firestore).\n4. **Insecure Design:** Handled via strict RBAC and Serverless API isolation.\n5. **Security Misconfiguration:** Managed via Vercel's automated, secure-by-default infrastructure.\n6. **Vulnerable Components:** Dependencies are routinely audited using \`npm audit\`.\n7. **Identification/Auth Failures:** Handled entirely by Google Firebase Auth.\n8. **Software/Data Integrity:** Webhooks are cryptographically verified.\n9. **Security Logging:** Sensitive administrative actions are written to an append-only \`audit_logs\` collection.\n10. **SSRF:** The platform does not make unverified outbound server requests based on user input.`,

  // 10-Deployment
  '10-Deployment/Vercel Deployment.md': `# Vercel Deployment\n\nPlaySphere is optimized for deployment on Vercel, the native hosting platform for Next.js applications.\n\n## Architecture\n- **Static Pages:** Pre-rendered at build time and served via Vercel's Global Edge CDN.\n- **Dynamic Routes:** Executed on-demand via Vercel Serverless Functions (Node.js/Edge).\n- **Assets:** Images and static files are automatically optimized and cached at the Edge.\n\n## Deployment Process\nDeployments are automated through a GitHub integration. Pushing to the \`main\` branch triggers a production build, while pushing to feature branches creates isolated Preview Deployments.`,

  '10-Deployment/CI-CD Pipeline.md': `# CI-CD Pipeline\n\nPlaySphere utilizes Vercel's built-in Continuous Integration and Continuous Deployment (CI/CD) pipeline.\n\n## Pipeline Stages\n1. **Code Commit:** Developer pushes code to GitHub.\n2. **Build Trigger:** Vercel intercepts the webhook and provisions a build container.\n3. **Dependency Installation:** \`npm install\` is executed with cache utilization.\n4. **Build Compilation:** \`npm run build\` generates the Next.js optimized production bundle.\n5. **Deployment:** The bundle is distributed across the Edge network.\n6. **Verification:** The deployment is assigned a unique, immutable URL (for previews) or mapped to the production domain.`,

  '10-Deployment/Domain & DNS.md': `# Domain & DNS\n\n## Configuration\n- **Registrar:** Custom domains are connected via Vercel's dashboard.\n- **DNS Records:** \n  - A Record: Points to Vercel's Anycast IP (\`76.76.21.21\`).\n  - CNAME Record: Points \`www\` to \`cname.vercel-dns.com\`.\n\n## Propagation\nVercel automatically verifies DNS propagation and issues the SSL certificate before routing live traffic to the domain.`,

  '10-Deployment/SSL.md': `# SSL (TLS)\n\n## Automated Provisioning\nPlaySphere does not require manual SSL certificate management. Vercel automatically provisions and renews SSL/TLS certificates via Let's Encrypt for all custom domains connected to the project.\n\n## Security Level\n- Minimum TLS Version: 1.2 (TLS 1.3 preferred).\n- Cipher Suites: Modern, strong ciphers enforced by Vercel's load balancers.`,

  '10-Deployment/Environment Variables.md': `# Environment Variables (Deployment)\n\n## Vercel Dashboard Configuration\nAll environment variables must be configured in the Vercel Dashboard under **Project Settings > Environment Variables**.\n\n## Multiline Variables\n> **CRITICAL:** The \`FIREBASE_PRIVATE_KEY\` contains multiline \`\\n\` characters. When pasting this into Vercel, it must be enclosed in double quotes or properly formatted to ensure the Node.js environment parses the line breaks correctly. Failure to do so will result in a \`500 Internal Server Error\` during Admin SDK initialization.`,

  '10-Deployment/Rollback Strategy.md': `# Rollback Strategy\n\nIn the event of a critical production failure, PlaySphere leverages Vercel's instant rollback capabilities.\n\n## Execution\n1. Navigate to the **Deployments** tab in the Vercel Dashboard.\n2. Locate the previous stable production deployment.\n3. Click the vertical ellipsis (three dots) and select **"Promote to Production"** or **"Revert"**.\n4. The routing layer will instantly switch traffic to the stable build without requiring a full recompilation.\n\n## Database Rollbacks\nFirestore does not support one-click rollbacks. If a bad deployment corrupted database state, point-in-time recovery (if enabled in GCP) or manual data patching scripts must be executed.`,

  // 11-Testing
  '11-Testing/Test Strategy.md': `# Test Strategy\n\n> **Note:** Based on the current codebase analysis, a formal automated testing suite (e.g., Jest, Cypress) is not yet implemented. The following document outlines the recommended Test Strategy for the future roadmap.\n\n## Objectives\n- Ensure booking logic strictly prevents double-bookings.\n- Verify Razorpay webhook handlers and signature validation.\n- Ensure RBAC correctly restricts access to administrative dashboards.\n\n## Approach\n- **Unit Testing:** Isolate and test individual utility functions and service layer logic.\n- **Integration Testing:** Test API endpoints interfacing with the Firebase Emulator.\n- **E2E Testing:** Simulate real user flows (login -> search -> book -> checkout) in a headless browser.`,

  '11-Testing/Unit Testing.md': `# Unit Testing\n\n> **Note:** Recommended implementation for future roadmap.\n\n## Framework\n- **Jest:** For executing JavaScript/TypeScript unit tests.\n- **React Testing Library:** For rendering and asserting component states.\n\n## Target Areas\n- **Components:** Verify conditional rendering in \`TurfCard.tsx\` and \`BookingForm.tsx\`.\n- **Services:** Mock Firebase and Razorpay calls in \`services/booking.service.ts\` to ensure correct success/error payloads are returned.`,

  '11-Testing/Integration Testing.md': `# Integration Testing\n\n> **Note:** Recommended implementation for future roadmap.\n\n## Framework\n- **Supertest / Next.js Test APIs:** For executing HTTP requests against local \`/api/*\` routes.\n- **Firebase Local Emulator Suite:** For testing Firestore queries and Security Rules without affecting production data.\n\n## Target Areas\n- Payment Verification API (\`/api/payment/verify\`).\n- Offline Booking API (\`/api/booking/offline\`).`,

  '11-Testing/API Testing.md': `# API Testing\n\n> **Note:** Recommended implementation for future roadmap.\n\n## Strategy\nAPI testing ensures the Next.js serverless functions return expected status codes and payloads.\n\n## Key Test Cases\n1. **POST \`/api/booking/offline\`**: Provide an already booked slot -> Expect \`409 Conflict\`.\n2. **POST \`/api/payment/verify\`**: Provide an invalid signature -> Expect \`500\` or \`400\` error and ensure booking is NOT written to DB.`,

  '11-Testing/UI Testing.md': `# UI Testing\n\n> **Note:** Recommended implementation for future roadmap.\n\n## Framework\n- **Cypress or Playwright:** For End-to-End (E2E) UI testing.\n\n## Critical Paths to Automate\n1. User Authentication (Login/Logout).\n2. Turf Search & Filter functionality.\n3. The complete booking flow (intercepting network requests to mock Razorpay).\n4. Owner Dashboard offline booking creation.`,

  '11-Testing/Performance Testing.md': `# Performance Testing\n\n## Lighthouse Audits\nPlaySphere's frontend should be routinely audited using Google Lighthouse (available in Chrome DevTools) to monitor:\n- **First Contentful Paint (FCP)**\n- **Largest Contentful Paint (LCP)**\n- **Cumulative Layout Shift (CLS)**\n- **Time to Interactive (TTI)**\n\n## Current Status\nRecent architectural optimizations shifted heavy database queries from Client-Side rendering to Next.js Server Components, significantly improving TTI and LCP scores for the Homepage and Search views.`,

  '11-Testing/Security Testing.md': `# Security Testing\n\n## Manual Auditing\n- **Firestore Rules:** Routinely tested in the Firebase Console Rules Playground to ensure simulated unauthorized reads/writes are denied.\n- **Dependency Scanning:** Execution of \`npm audit\` during the build pipeline to catch vulnerable third-party packages.\n\n> **Roadmap Recommendation:** Integrate automated security scanning tools (e.g., Snyk) into the GitHub Actions pipeline.`,

  // 12-Monitoring
  '12-Monitoring/Logging.md': `# Logging\n\nPlaySphere utilizes distinct logging mechanisms for different environments.\n\n## Client-Side Logging\n- \`console.log\` and \`console.error\` are used for development debugging.\n- *Recommendation:* Strip \`console.log\` statements in the production build via the \`next.config.mjs\` compiler options.\n\n## Server-Side Logging\n- Errors occurring in Next.js API routes are logged to stdout.\n- These logs are accessible via the **Vercel Dashboard -> Logs** tab, which aggregates runtime logs from the serverless functions.\n\n## Audit Logging (Database)\nCritical administrative actions (e.g., Owner creating an offline booking) are permanently written to the \`audit_logs\` Firestore collection for security accountability.`,

  '12-Monitoring/Monitoring.md': `# Monitoring\n\n## Vercel Analytics\nPlaySphere leverages Vercel's built-in monitoring tools to track:\n- Serverless function execution times.\n- 4xx and 5xx error rates.\n- Bandwidth consumption.\n\n## Firebase Console\nThe Firebase Dashboard monitors:\n- Firestore read/write/delete operations (crucial for cost management).\n- Authentication success/failure rates.\n- Storage bucket egress.`,

  '12-Monitoring/Analytics.md': `# Analytics\n\n## Business Analytics (Dashboard)\nPlaySphere provides internal analytics directly to Turf Owners via the \`/owner/dashboard\` route, calculating:\n- Total Revenue\n- Total Bookings\n- Active Turfs\n\n## Web Analytics\n> **Roadmap Recommendation:** Integrate Google Analytics (GA4) or Vercel Web Analytics to track user journeys, page views, and conversion rates (drop-off points during the booking flow).`,

  '12-Monitoring/Error Tracking.md': `# Error Tracking\n\n> **Note:** Based on the current codebase analysis, a dedicated error tracking service is not yet integrated. It is documented here as a recommendation for the future roadmap.\n\n## Recommended Implementation: Sentry\nIntegrating Sentry for Next.js is highly recommended for production to catch unhandled exceptions:\n1. **Client-Side:** Catches React render errors and network failures.\n2. **Server-Side:** Catches API route crashes, signature verification failures, and Firestore connection issues.\n3. **Alerting:** Sends real-time Slack or Email alerts when spike in \`500\` errors occurs.`,

  '12-Monitoring/Alerting.md': `# Alerting\n\n> **Note:** Automated alerting is not currently configured. It is documented here as a recommendation for the future roadmap.\n\n## Recommended Configuration\n- **Vercel Checks:** Configure Slack integrations in Vercel to alert the engineering team of failed deployments.\n- **Firebase Budget Alerts:** Crucial for NoSQL databases. Configure Google Cloud Billing alerts to trigger an email if Firestore read operations spike unexpectedly (preventing billing attacks/runaways).\n- **Uptime Monitoring:** Utilize a service like UptimeRobot or BetterStack to ping the homepage every 5 minutes and alert the team if the site goes down.`
};

for (const [relPath, content] of Object.entries(docs)) {
  const fullPath = path.join(rootDir, relPath);
  fs.writeFileSync(fullPath, content, 'utf8');
}
console.log('Successfully generated batch 4.');
