const fs = require('fs');
const path = require('path');

const rootDir = 'c:/Users/Lenovo/Downloads/playsphere-main-main/playsphere-main-main/PlaySphere-Documentation';

const docs = {
  // 03-System-Design
  '03-System-Design/Software Design Document (SDD).md': `# Software Design Document (SDD)\n\n## 1. Introduction\nThis document describes the high-level architecture and software design of the PlaySphere platform, encompassing the frontend PWA, the serverless backend API, and the NoSQL database layer.\n\n## 2. Design Principles\n- **Stateless Architecture:** Utilizing Next.js serverless functions ensures horizontal scalability and eliminates server-side session management bottlenecks.\n- **Component-Based UI:** React components are modular, reusable, and styled dynamically via Tailwind CSS.\n- **Optimistic UI Updates:** The frontend implements optimistic rendering to provide instantaneous feedback to users while background network requests complete.\n- **Zero-Trust Security:** Firebase Admin SDK is used for sensitive operations, ensuring client-side requests cannot bypass business logic or database rules.\n\n## 3. Technology Stack\n- **Frontend:** Next.js 15, React 18/19, Tailwind CSS, Shadcn UI\n- **Backend:** Next.js API Routes (Serverless), Firebase Admin SDK\n- **Database:** Firebase Firestore (NoSQL Document Store)\n- **Authentication:** Firebase Auth (JWT)\n- **Hosting:** Vercel (Edge Network)`,

  '03-System-Design/Architecture.md': `# Architecture\n\nPlaySphere implements a decoupled, serverless architecture leveraging the Jamstack philosophy.\n\n## Core Architecture Components\n\n### 1. Client Layer (Browser / PWA)\n- Responsible for rendering the UI, handling user interactions, and maintaining local state.\n- Interfaces directly with Firebase Client SDKs for real-time data fetching (where rules permit).\n\n### 2. Application Layer (Next.js Server / Vercel Edge)\n- Handles Server-Side Rendering (SSR) for SEO-critical pages.\n- Acts as an API Gateway for secure operations (Payments, Offline Bookings) via \`/api/*\` routes.\n\n### 3. Data Layer (Firebase Firestore)\n- Stores all persistent application data in scalable NoSQL document collections.\n- Triggers real-time snapshot updates to subscribed clients.\n\n### 4. Integration Layer\n- Interfaces with external services like Razorpay via secure webhook endpoints and signed API requests.\n\n## High-Level Architecture Diagram\n\`\`\`mermaid\ngraph TD\n    Client[Client Browser / PWA] -->|HTTPS| NextJS[Next.js App Router]\n    Client -->|WebSocket| Firestore[Firebase Firestore]\n    Client -->|HTTPS| FirebaseAuth[Firebase Auth]\n    \n    NextJS -->|Serverless Functions| AdminSDK[Firebase Admin SDK]\n    NextJS <-->|API Calls & Webhooks| Razorpay[Razorpay API]\n    \n    AdminSDK -->|Privileged Access| Firestore\n\`\`\``,

  '03-System-Design/Data Flow Diagram.md': `# Data Flow Diagram\n\nThe following diagram illustrates the primary data flow for the core booking and payment process.\n\n## Level 1 Data Flow\n\n\`\`\`mermaid\ngraph LR\n    Player((Player)) -->|1. Searches Turfs| UI[Frontend UI]\n    UI -->|2. Fetches Inventory| DB[(Firestore DB)]\n    UI -->|3. Initiates Booking| API[Next.js API]\n    API -->|4. Creates Order| Gateway[Razorpay]\n    Gateway -->|5. Returns Order ID| API\n    API -->|6. Passes ID| UI\n    Player -->|7. Completes Payment| Gateway\n    Gateway -->|8. Webhook/Verification| API\n    API -->|9. Confirms Booking| DB\n    DB -->|10. Triggers Update| Owner((Turf Owner))\n\`\`\``,

  '03-System-Design/Component Diagram.md': `# Component Diagram\n\nThis diagram outlines the logical component structure of the PlaySphere application.\n\n\`\`\`mermaid\ncomponentDiagram\n    package "Frontend (Next.js Client)" {\n        [App Context Providers] \n        [UI Components (Shadcn)]\n        [Page Routing]\n        [PWA Service Worker]\n    }\n\n    package "Backend (Next.js Server)" {\n        [API Route Controllers]\n        [Firebase Admin Services]\n        [Payment Verifier]\n    }\n\n    package "External Services" {\n        [Firebase Auth API]\n        [Firestore Database]\n        [Razorpay Gateway]\n    }\n\n    [App Context Providers] --> [Page Routing]\n    [Page Routing] --> [UI Components (Shadcn)]\n    [UI Components (Shadcn)] --> [API Route Controllers]: HTTPS Requests\n    [UI Components (Shadcn)] --> [Firebase Auth API]: Authentication\n    [UI Components (Shadcn)] --> [Firestore Database]: Client Reads\n    \n    [API Route Controllers] --> [Firebase Admin Services]\n    [API Route Controllers] --> [Payment Verifier]\n    [Firebase Admin Services] --> [Firestore Database]: Admin Writes\n    [Payment Verifier] --> [Razorpay Gateway]: Signature Validation\n\`\`\``,

  '03-System-Design/Sequence Diagram.md': `# Sequence Diagram\n\nThe following sequence diagram details the strict interaction flow for creating an online booking with payment verification.\n\n\`\`\`mermaid\nsequenceDiagram\n    actor Player\n    participant UI as Next.js Client\n    participant API as /api/payment/verify\n    participant DB as Firestore\n    participant Razorpay\n\n    Player->>UI: Selects Slot & Clicks "Book"\n    UI->>DB: Check slot availability\n    DB-->>UI: Slot available\n    UI->>Razorpay: Initialize Checkout (Amount)\n    Razorpay-->>Player: Display Payment Modal\n    Player->>Razorpay: Enters Payment Details\n    Razorpay-->>UI: Returns razorpay_payment_id & signature\n    UI->>API: POST /api/payment/verify (Payload)\n    Note over API: Verifies HMAC SHA256 Signature\n    API->>DB: create() Booking Document\n    DB-->>API: Success\n    API-->>UI: 200 OK (Booking Confirmed)\n    UI-->>Player: Display Success & Check-in OTP\n\`\`\``,

  '03-System-Design/Class Diagram.md': `# Class Diagram\n\nThe following diagram represents the core data models and their relational references within the NoSQL schema.\n\n\`\`\`mermaid\nclassDiagram\n    class User {\n        +String uid\n        +String role (player, owner, admin)\n        +String name\n        +String email\n        +String phone\n        +Timestamp createdAt\n    }\n\n    class Turf {\n        +String id\n        +String ownerId\n        +String name\n        +String location\n        +Number price\n        +Array sports\n        +Array images\n        +Boolean isActive\n    }\n\n    class Booking {\n        +String id\n        +String turfId\n        +String ownerId\n        +String playerId\n        +String date\n        +String slot\n        +String status (pending, confirmed, cancelled)\n        +String paymentId\n        +String otp\n    }\n\n    class Payment {\n        +String id\n        +String bookingId\n        +String amount\n        +String method\n        +String razorpayPaymentId\n        +String status\n    }\n\n    User "1" -- "*" Turf : owns\n    User "1" -- "*" Booking : makes\n    Turf "1" -- "*" Booking : hosts\n    Booking "1" -- "1" Payment : requires\n\`\`\``,

  '03-System-Design/ER Diagram.md': `# ER Diagram\n\nWhile Firestore is a NoSQL database, the logical entity relationships are modeled as follows to maintain data integrity.\n\n\`\`\`mermaid\nerDiagram\n    USERS ||--o{ TURFS : "manages (if owner)"\n    USERS ||--o{ BOOKINGS : "books (if player)"\n    TURFS ||--o{ BOOKINGS : "contains"\n    BOOKINGS ||--o| PAYMENTS : "generates"\n    TURFS ||--o{ REVIEWS : "receives"\n    USERS ||--o{ REVIEWS : "writes"\n\n    USERS {\n        string uid PK\n        string email\n        string role\n    }\n    TURFS {\n        string id PK\n        string ownerId FK\n        string name\n        number price\n    }\n    BOOKINGS {\n        string id PK\n        string turfId FK\n        string playerId FK\n        string status\n    }\n    PAYMENTS {\n        string id PK\n        string bookingId FK\n        string amount\n        string transactionId\n    }\n\`\`\``,

  '03-System-Design/Deployment Diagram.md': `# Deployment Diagram\n\nThe deployment architecture highlights the cloud-native, serverless distribution of PlaySphere.\n\n\`\`\`mermaid\ngraph TD\n    subgraph User Devices\n        Mobile[Mobile Device (PWA)]\n        Desktop[Desktop Browser]\n    end\n\n    subgraph Vercel Edge Network\n        CDN[Global CDN]\n        SSR[Next.js Serverless Functions]\n    end\n\n    subgraph Google Cloud Platform\n        Auth[Firebase Authentication]\n        DB[(Firestore Database)]\n        Storage[Firebase Cloud Storage]\n    end\n\n    subgraph Third-Party Services\n        Razorpay[Razorpay Payment Gateway]\n    end\n\n    Mobile -->|HTTPS| CDN\n    Desktop -->|HTTPS| CDN\n    CDN -->|Dynamic Routes| SSR\n    \n    SSR -->|Admin SDK| DB\n    Mobile -->|Client SDK| DB\n    Desktop -->|Client SDK| Auth\n    \n    SSR <-->|API| Razorpay\n\`\`\``,

  // 04-Database
  '04-Database/Firestore Schema.md': `# Firestore Schema\n\nPlaySphere utilizes Google Cloud Firestore, a flexible, scalable NoSQL cloud database. Data is stored in documents, which are organized into collections.\n\n## Root Collections\n1. \`users\`: Platform user profiles and RBAC definitions.\n2. \`turfs\`: Sports venue profiles and configuration.\n3. \`bookings\`: Core transactional reservation data.\n4. \`payments\`: Payment ledger for reconciliation.\n5. \`audit_logs\`: Secure, append-only logs for administrative actions.\n\n## Design Philosophy\n- **Denormalization:** Some data (like \`turfName\` or \`playerName\`) is duplicated within the \`bookings\` collection to avoid heavy client-side joins and reduce document read counts.\n- **Shallow Queries:** Collections are kept flat. Subcollections are avoided for core transactional data to allow global querying via standard indexes.`,

  '04-Database/Users Collection.md': `# Users Collection\n\n**Collection Path:** \`/users/{uid}\`\n\nStores user profiles, roles, and contact information. The \`uid\` matches the Firebase Authentication UUID.\n\n## Document Structure\n\`\`\`json\n{\n  \"uid\": \"string\",\n  \"email\": \"string\",\n  \"name\": \"string\",\n  \"role\": \"string (player | owner | admin)\",\n  \"phone\": \"string (optional)\",\n  \"createdAt\": \"timestamp\",\n  \"updatedAt\": \"timestamp\"\n}\n\`\`\`\n\n## Security Rules\n- **Read:** A user can only read their own document. Super Admins can read all.\n- **Write:** Users can update their own non-privileged fields (name, phone). Only Super Admins can change the \`role\` field.`,

  '04-Database/Turfs Collection.md': `# Turfs Collection\n\n**Collection Path:** \`/turfs/{turfId}\`\n\nStores the venue details, pricing, and operating configuration.\n\n## Document Structure\n\`\`\`json\n{\n  \"ownerId\": \"string (FK: users.uid)\",\n  \"name\": \"string\",\n  \"city\": \"string\",\n  \"address\": \"string\",\n  \"price\": \"number\",\n  \"sports\": [\"string (e.g. Football, Cricket)\"],\n  \"amenities\": [\"string\"],\n  \"images\": [\"string (URLs)\"],\n  \"operatingHours\": {\n    \"open\": \"string (HH:MM)\",\n    \"close\": \"string (HH:MM)\"\n  },\n  \"isActive\": \"boolean\",\n  \"createdAt\": \"timestamp\"\n}\n\`\`\`\n\n## Security Rules\n- **Read:** Publicly readable if \`isActive == true\`. Owners can read their own regardless of status.\n- **Write:** Only the authenticated user matching \`ownerId\` can update the document.`,

  '04-Database/Bookings Collection.md': `# Bookings Collection\n\n**Collection Path:** \`/bookings/{bookingId}\`\n\nCore transactional collection representing reserved time slots.\n\n## Document Structure\n\`\`\`json\n{\n  \"turfId\": \"string (FK: turfs.id)\",\n  \"turfName\": \"string (Denormalized)\",\n  \"ownerId\": \"string (FK: users.uid)\",\n  \"playerId\": \"string (FK: users.uid - Null for offline)\",\n  \"playerName\": \"string\",\n  \"date\": \"string (YYYY-MM-DD)\",\n  \"slot\": \"string (HH:MM)\",\n  \"status\": \"string (pending | confirmed | cancelled | checked_in | refunded)\",\n  \"bookingType\": \"string (online | offline)\",\n  \"price\": \"number\",\n  \"otp\": \"string (4-digit)\",\n  \"otpVerified\": \"boolean\",\n  \"paymentId\": \"string (Optional)\",\n  \"createdAt\": \"timestamp\"\n}\n\`\`\`\n\n## Deterministic ID Strategy (Offline Bookings)\nFor offline bookings, the document ID is deterministically generated as \`turfId_date_slot\` to guarantee a slot cannot be booked twice simultaneously at the database level using Firestore's \`create()\` method constraint.`,

  '04-Database/Payments Collection.md': `# Payments Collection\n\n**Collection Path:** \`/payments/{paymentId}\`\n\nFinancial ledger storing metadata returned from the payment gateway (Razorpay).\n\n## Document Structure\n\`\`\`json\n{\n  \"bookingId\": \"string (FK: bookings.id)\",\n  \"playerId\": \"string (FK: users.uid)\",\n  \"razorpayOrderId\": \"string\",\n  \"razorpayPaymentId\": \"string\",\n  \"razorpaySignature\": \"string\",\n  \"amount\": \"number\",\n  \"currency\": \"string\",\n  \"status\": \"string (captured | failed | refunded)\",\n  \"createdAt\": \"timestamp\"\n}\n\`\`\`\n\n## Security Rules\n- **Read:** Accessible only by the respective \`playerId\` or Super Admin.\n- **Write:** STRICTLY written by the Server (Admin SDK) during the webhook/verification flow. Client writes are explicitly denied.`,

  '04-Database/Notifications Collection.md': `# Notifications Collection\n\n> **Note:** Based on the current codebase analysis, this feature is not yet implemented. It is documented here as a recommendation for the future roadmap.\n\n**Collection Path:** \`/notifications/{notificationId}\`\n\nIntended to store in-app alerts for users (e.g., booking confirmations, cancellations, promotional messages).\n\n## Recommended Structure\n\`\`\`json\n{\n  \"userId\": \"string\",\n  \"title\": \"string\",\n  \"body\": \"string\",\n  \"type\": \"string (booking | system | promo)\",\n  \"isRead\": \"boolean\",\n  \"createdAt\": \"timestamp\"\n}\n\`\`\``,

  '04-Database/Reviews Collection.md': `# Reviews Collection\n\n> **Note:** Based on the current codebase analysis, this feature is not yet implemented. It is documented here as a recommendation for the future roadmap.\n\n**Collection Path:** \`/reviews/{reviewId}\`\n\nIntended to store player feedback and ratings for turfs.\n\n## Recommended Structure\n\`\`\`json\n{\n  \"turfId\": \"string\",\n  \"playerId\": \"string\",\n  \"playerName\": \"string\",\n  \"rating\": \"number (1-5)\",\n  \"comment\": \"string\",\n  \"createdAt\": \"timestamp\"\n}\n\`\`\``,

  '04-Database/Settlements Collection.md': `# Settlements Collection\n\n> **Note:** Based on the current codebase analysis, this feature is not yet implemented. It is documented here as a recommendation for the future roadmap.\n\n**Collection Path:** \`/settlements/{settlementId}\`\n\nIntended to track financial payouts from the platform to the turf owners.\n\n## Recommended Structure\n\`\`\`json\n{\n  \"ownerId\": \"string\",\n  \"amount\": \"number\",\n  \"periodStart\": \"timestamp\",\n  \"periodEnd\": \"timestamp\",\n  \"status\": \"string (pending | processing | completed)\",\n  \"transactionRef\": \"string\",\n  \"createdAt\": \"timestamp\"\n}\n\`\`\``,

  '04-Database/Analytics Collection.md': `# Analytics Collection\n\n**Collection Path:** \`/audit_logs/{logId}\` (Used for analytical and security tracking)\n\nStores immutable system events for administrative oversight.\n\n## Document Structure\n\`\`\`json\n{\n  \"action\": \"string (e.g. OFFLINE_BOOKING_CREATED)\",\n  \"turfId\": \"string\",\n  \"ownerId\": \"string\",\n  \"details\": \"string\",\n  \"timestamp\": \"timestamp\"\n}\n\`\`\`\n\n## Security Rules\n- **Read/Write:** Client access is strictly denied. All writes to this collection occur via the Firebase Admin SDK on the server (e.g., inside Next.js API routes).`,

  '04-Database/Database Indexes.md': `# Database Indexes\n\nFirestore requires explicit composite indexes for queries involving multiple fields, or queries combining equality filters with range/sorting filters on different fields.\n\n## Required Composite Indexes\n\nThe following indexes must be manually created in the Firebase Console to ensure proper functionality of the application:\n\n### Collection: \`bookings\`\nUsed primarily by the Turf Owner Dashboard to fetch their bookings in chronological order.\n- **Field 1:** \`ownerId\` (Ascending)\n- **Field 2:** \`createdAt\` (Descending)\n- **Query Scope:** Collection\n\n### Collection: \`bookings\`\nUsed by the checking algorithm to detect overlapping bookings for a specific slot.\n- **Field 1:** \`turfId\` (Ascending)\n- **Field 2:** \`date\` (Ascending)\n- **Field 3:** \`slot\` (Ascending)\n- **Query Scope:** Collection\n\n## Management\nThese indexes can be deployed automatically if a \`firestore.indexes.json\` file is created and deployed via the Firebase CLI (\`firebase deploy --only firestore:indexes\`).`
};

for (const [relPath, content] of Object.entries(docs)) {
  const fullPath = path.join(rootDir, relPath);
  fs.writeFileSync(fullPath, content, 'utf8');
}
console.log('Successfully generated batch 2.');
