const fs = require('fs');
const path = require('path');

const rootDir = 'c:/Users/Lenovo/Downloads/playsphere-main-main/playsphere-main-main/PlaySphere-Documentation';

const docs = {
  '00-Introduction/Vision & Mission.md': `# Vision & Mission\n\n## Vision\nTo become the ubiquitous digital infrastructure powering the global sports and recreational facility ecosystem, fostering active communities through seamless accessibility.\n\n## Mission\nTo empower sports facility owners with enterprise-grade management tools that optimize utilization and revenue, while providing players with a frictionless, transparent, and instant booking experience. We aim to eliminate the friction between the desire to play and the ability to find a venue.`,

  '00-Introduction/Problem Statement.md': `# Problem Statement\n\nThe recreational sports venue ecosystem suffers from significant operational inefficiencies and disjointed user experiences:\n\n## For Facility Owners\n- **Manual Ledger Management:** Reliance on physical ledgers or fragmented spreadsheets leads to double-bookings, revenue leakage, and inefficient time utilization.\n- **Lack of Analytics:** Inability to track peak hours, revenue trends, and customer retention metrics.\n- **Payment Inefficiencies:** Manual collection of cash or unverified P2P transfers results in reconciliation challenges and delayed settlements.\n- **High No-Show Rates:** Without upfront secure payments, owners face revenue loss from unfulfilled reservations.\n\n## For Players\n- **Discovery Friction:** Difficulty in finding available local turfs without making multiple phone calls.\n- **Lack of Transparency:** Opaque pricing and unavailability of real-time slot information.\n- **Poor Booking Experience:** Cumbersome manual booking processes lacking instant confirmation and secure digital payments.`,

  '00-Introduction/Solution.md': `# Solution\n\nPlaySphere provides a unified, full-stack digital solution addressing the pain points of both turf owners and players:\n\n## Comprehensive Owner Dashboard\n- **Centralized Slot Management:** Real-time calendar synchronization to manage online and offline bookings in a single view.\n- **Automated Financial Reconciliation:** Integrated Razorpay gateways ensure that payments are verified, tracked, and automatically settled.\n- **Business Intelligence:** Automated generation of metrics including total revenue, booking volume, and customer trends.\n\n## Frictionless Player Experience\n- **Real-Time Discovery & Booking:** Intuitive PWA interface allowing users to search, filter, and book available slots instantly.\n- **Secure Digital Payments:** Instant, secure checkout process utilizing industry-standard payment gateways.\n- **Instant Confirmation:** Automated OTP generation and booking confirmation for secure check-ins at the venue.\n\n## Architectural Advantages\n- **Cloud-Native Scalability:** Built on Next.js and Firebase, ensuring high availability and instant responsiveness even during peak traffic.\n- **Offline Resiliency:** PWA architecture allows users to install the application natively and interact smoothly under poor network conditions.`,

  '00-Introduction/Objectives.md': `# Objectives\n\n## Business Objectives\n- Digitally transform the operations of local sports facilities.\n- Reduce booking abandonment rates through a streamlined checkout process.\n- Minimize revenue leakage for facility owners by enforcing upfront digital payments.\n\n## Technical Objectives\n- Achieve a sub-second Time To Interactive (TTI) utilizing Next.js Server Components.\n- Maintain 99.9% uptime leveraging Firebase's distributed NoSQL architecture.\n- Ensure strict data integrity and access control through comprehensive Firestore Security Rules and server-side validation.\n- Provide a native-app-like experience via Progressive Web App (PWA) technologies without the overhead of app store deployment.\n\n## Security Objectives\n- Prevent unauthorized data access using Role-Based Access Control (RBAC).\n- Secure financial transactions via server-to-server Razorpay signature verification.\n- Protect against common web vulnerabilities (XSS, CSRF) through rigorous framework-level protections.`,

  '00-Introduction/Business Model.md': `# Business Model\n\nPlaySphere operates on a scalable B2B2C (Business-to-Business-to-Consumer) SaaS marketplace model.\n\n## Revenue Streams\n\n### 1. Transaction Commission (Take Rate)\n- A percentage-based commission is levied on every successful online booking processed through the platform.\n- This covers payment gateway fees, platform maintenance, and customer support.\n\n### 2. SaaS Subscription (Future Roadmap)\n- Tiered monthly or annual subscription plans for Turf Owners.\n- **Basic Tier:** Essential booking and ledger management.\n- **Premium Tier:** Advanced analytics, priority placement in search results, SMS/WhatsApp notification integrations, and multi-staff management.\n\n### 3. Featured Listings\n- Promoted slots within the player search interface, allowing owners to boost visibility for underutilized slots or off-peak hours.\n\n## Value Proposition\n- **For Owners:** Increased utilization rates, automated administrative tasks, and guaranteed upfront payments.\n- **For Players:** Convenience, transparency, and a guaranteed slot upon arrival.`,

  '00-Introduction/Target Users.md': `# Target Users\n\nPlaySphere is designed for a dual-sided marketplace, catering to distinct user archetypes with specialized interfaces and capabilities.\n\n## 1. Players (Consumers)\n- **Demographic:** Sports enthusiasts, amateur athletes, corporate teams, and weekend warriors (typically aged 16-45).\n- **Core Needs:** Quick discovery of nearby venues, transparent pricing, instant booking confirmation, and secure payment processing.\n- **Interface:** Mobile-first Progressive Web App (PWA) optimized for speed and ease of use.\n\n## 2. Turf Owners (Businesses)\n- **Demographic:** Sports facility proprietors, local club managers, and multi-venue operators.\n- **Core Needs:** Elimination of double bookings, automated payment reconciliation, business analytics, and staff management.\n- **Interface:** Comprehensive desktop and tablet-optimized administrative dashboard.\n\n## 3. System Administrators (Internal)\n- **Demographic:** PlaySphere operations and support teams.\n- **Core Needs:** Platform-wide oversight, user/turf verification, dispute resolution, and global financial reconciliation.\n- **Interface:** Secure, internal Admin Dashboard with elevated privileges (Super Admin).`,
  
  '01-Getting-Started/README.md': `# PlaySphere\n\n![PlaySphere Banner](https://via.placeholder.com/1200x300?text=PlaySphere+Enterprise+Sports+Platform)\n\nPlaySphere is a modern, enterprise-grade sports venue booking and management platform built with Next.js 15, Firebase, and Razorpay. It provides a seamless PWA experience for players to discover and book turfs, and a robust administrative dashboard for turf owners to manage inventory and revenue.\n\n## Key Features\n- ⚡ **Server-Side Rendering (SSR)** via Next.js App Router for optimal performance and SEO.\n- 🔒 **Enterprise Security** via Firebase Authentication and strict Firestore rules.\n- 💳 **Secure Transactions** powered by Razorpay with automated settlements.\n- 📱 **Progressive Web App (PWA)** for native-like mobile experiences.\n- 📊 **Real-time Analytics** for turf owners.\n\n## Documentation\nPlease refer to the complete documentation suite in the \`PlaySphere-Documentation/\` directory for detailed architecture, API, and deployment guidelines.`,

  '01-Getting-Started/Installation Guide.md': `# Installation Guide\n\nFollow these steps to set up PlaySphere on a local development machine.\n\n## Step 1: Clone the Repository\n\`\`\`bash\ngit clone https://github.com/your-org/playsphere.git\ncd playsphere\n\`\`\`\n\n## Step 2: Install Dependencies\nPlaySphere uses \`npm\` for package management.\n\`\`\`bash\nnpm install\n\`\`\`\n\n## Step 3: Configure Environment Variables\nCopy the example environment file and populate it with your Firebase and Razorpay credentials.\n\`\`\`bash\ncp .env.example .env.local\n\`\`\`\n*(Refer to \`Environment Setup.md\` for exact variable requirements).*\n\n## Step 4: Run the Development Server\n\`\`\`bash\nnpm run dev\n\`\`\`\nThe application will be available at \`http://localhost:3000\`.\n\n## Step 5: Build for Production\nTo simulate a production build locally:\n\`\`\`bash\nnpm run build\nnpm run start\n\`\`\``,

  '01-Getting-Started/Prerequisites.md': `# Prerequisites\n\nBefore deploying or contributing to PlaySphere, ensure the following tools and accounts are configured:\n\n## System Requirements\n- **Node.js:** v18.17.0 or higher (v20+ recommended).\n- **Package Manager:** npm (v9 or higher).\n- **Git:** v2.30.0 or higher.\n- **OS:** Linux, macOS, or Windows (WSL2 recommended).\n\n## Required Accounts & API Keys\n1. **Google Firebase Account:**\n   - Active Firebase Project.\n   - Firestore Database (Native Mode) enabled.\n   - Firebase Storage enabled.\n   - Firebase Authentication (Email/Password & Google OAuth) enabled.\n   - Firebase Admin Service Account JSON key.\n\n2. **Razorpay Account:**\n   - Active Merchant Account.\n   - Test/Live API Key ID and Key Secret.\n   - Webhook configured for \`payment.captured\`, \`refund.processed\`.\n\n3. **Vercel Account:**\n   - Account linked to the project's GitHub/GitLab repository for CI/CD deployments.`,

  '01-Getting-Started/Environment Setup.md': `# Environment Setup\n\nPlaySphere relies on secure environment variables to manage third-party integrations. These must be configured in \`.env.local\` for development and securely injected into the Vercel dashboard for production.\n\n## Required Variables\n\n\`\`\`env\n# Firebase Client Configuration (Safe to expose)\nNEXT_PUBLIC_FIREBASE_API_KEY=\"AIzaSy...\"\nNEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=\"playsphere-xyz.firebaseapp.com\"\nNEXT_PUBLIC_FIREBASE_PROJECT_ID=\"playsphere-xyz\"\nNEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=\"playsphere-xyz.appspot.com\"\nNEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=\"1234567890\"\nNEXT_PUBLIC_FIREBASE_APP_ID=\"1:1234567890:web:abcdef\"\n\n# Firebase Admin Configuration (STRICTLY CONFIDENTIAL)\n# Ensure the private key is properly formatted with \\n newlines in production\nFIREBASE_CLIENT_EMAIL=\"firebase-adminsdk-abc@playsphere-xyz.iam.gserviceaccount.com\"\nFIREBASE_PRIVATE_KEY=\"-----BEGIN PRIVATE KEY-----\\nMIIEvQIBAD...\\n-----END PRIVATE KEY-----\\n\"\n\n# Razorpay Configuration\nNEXT_PUBLIC_RAZORPAY_KEY_ID=\"rzp_test_1234567890\"\nRAZORPAY_KEY_SECRET=\"your_razorpay_secret_key\"\n\`\`\`\n\n## Security Notes\n- Never commit \`.env.local\` to version control.\n- Ensure \`.gitignore\` includes \`*.env*\`.\n- For Vercel deployment, the \`FIREBASE_PRIVATE_KEY\` must be enclosed in quotes if it contains multiline string representations.`,

  '01-Getting-Started/Folder Structure.md': `# Folder Structure\n\nPlaySphere adheres to the Next.js App Router conventions with a clear separation of concerns.\n\n\`\`\`text\nplaysphere/\n├── app/                      # Next.js App Router (Pages, Layouts, API Routes)\n│   ├── (auth)/               # Authentication routes (login, register)\n│   ├── api/                  # Server-side API endpoints (payment, offline booking)\n│   ├── owner/                # Turf Owner dashboard routes\n│   ├── player/               # Player dashboard routes\n│   ├── turfs/                # Public turf listing and details routes\n│   ├── layout.tsx            # Root layout containing global providers\n│   └── page.tsx              # Application homepage\n├── components/               # Reusable UI Components\n│   ├── auth/                 # Login/Signup forms\n│   ├── booking/              # Booking forms, slot pickers\n│   ├── dashboard/            # Admin/Owner dashboard widgets\n│   ├── landing/              # Homepage sections (Hero, Features)\n│   ├── turfs/                # Turf cards, lists, detail views\n│   └── ui/                   # Shadcn UI primitives (buttons, dialogs)\n├── context/                  # React Context Providers (AuthContext)\n├── firebase/                 # Firebase Client SDK initialization\n├── hooks/                    # Custom React Hooks (useDebounce, etc.)\n├── lib/                      # Utility libraries (Firebase Admin initialization, utils)\n├── public/                   # Static assets (images, icons, manifest.json)\n├── services/                 # Business logic and database access layer\n│   ├── auth.service.ts\n│   ├── booking.service.ts\n│   └── turf.service.ts\n├── types/                    # TypeScript interfaces and type definitions\n├── .env.example              # Environment variable template\n├── next.config.mjs           # Next.js configuration (PWA, domains)\n├── package.json              # Project dependencies and scripts\n├── tailwind.config.ts        # Tailwind CSS configuration\n└── tsconfig.json             # TypeScript configuration\n\`\`\``,

  '01-Getting-Started/Tech Stack.md': `# Tech Stack\n\nPlaySphere is built on a modern, high-performance JavaScript stack.\n\n## Frontend\n- **Framework:** [Next.js 15](https://nextjs.org/) (App Router) - For Server-Side Rendering (SSR) and routing.\n- **Library:** [React 18/19](https://react.dev/) - Core UI library.\n- **Language:** [TypeScript](https://www.typescriptlang.org/) - For strict type safety and developer productivity.\n- **Styling:** [Tailwind CSS](https://tailwindcss.com/) - Utility-first CSS framework.\n- **Components:** [Shadcn UI](https://ui.shadcn.com/) - Accessible, customizable UI primitives (Radix UI).\n- **Icons:** [Lucide React](https://lucide.dev/) - Consistent iconography.\n\n## Backend & Database (BaaS)\n- **Authentication:** [Firebase Auth](https://firebase.google.com/docs/auth) - Secure email/password and OAuth providers.\n- **Database:** [Firebase Firestore](https://firebase.google.com/docs/firestore) - NoSQL document database with real-time listeners.\n- **Storage:** [Firebase Storage](https://firebase.google.com/docs/storage) - For turf images and user avatars.\n- **Admin SDK:** [Firebase Admin SDK](https://firebase.google.com/docs/admin/setup) - For secure server-side operations bypassing client security rules.\n\n## Payments\n- **Gateway:** [Razorpay](https://razorpay.com/) - Secure payment processing, order creation, and webhooks.\n\n## Infrastructure & DevOps\n- **Hosting:** [Vercel](https://vercel.com/) - Edge network deployment, CI/CD, and serverless functions execution.\n- **PWA:** [next-pwa](https://www.npmjs.com/package/next-pwa) - Service worker generation for offline support and installability.\n- **Package Manager:** npm - Dependency management.`
};

for (const [relPath, content] of Object.entries(docs)) {
  const fullPath = path.join(rootDir, relPath);
  fs.writeFileSync(fullPath, content, 'utf8');
}
console.log('Successfully generated batch 1.');
